name: Notificación de Cambios
on:
  push:
    branches: [ main ]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: 🚀 Nuevo Commit en ${{ github.repository }}" \
               -H "Priority: default" \
               -H "Tags: github,git" \
               -d "Repositorio: ${{ github.repository }}
                   Commit: ${{ github.sha }}
                   Autor: ${{ github.actor }}
                   Mensaje: ${{ github.event.head_commit.message }}" \
               https://ntfy.sh/devops-itla
